(define (key record) record)

(define (lookup given-key set-of-records)
  (cond ((null? set-of-records) false)
        ((equal? given-key (key (car set-of-records)))
         (car set-of-records))
        ((< given-key (key (car set-of-records)))
         (lookup given-key (cadr set-of-records)))
        ((> given-key (key (car set-of-records)))
         (lookup given-key (caddr set-of-records)))))
